version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
   build-and-test:
   working_directory: ~/Dev5_Werkstuk_ShiYuanKevinJi
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - node/install-packages
      - run: cd eindwerk_dev/package.json
       name: run test
      command: npm test


workflows:
  sample: 
    jobs:
      - build-and-test